import {
  Address,
  encodePacked,
  keccak256,
  recoverMessageAddress,
} from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

export interface ClaimKeyPair {
  claimPrivateKey: `0x${string}`;
  claimAddress: Address;
  claimKeyHash: `0x${string}`;
}

/**
 * Generates an ephemeral cryptographic keypair for link-based escrow deposits.
 * The private key stays in the URL fragment (#key=...) and is never sent to the backend.
 */
export function generateClaimKeyPair(): ClaimKeyPair {
  const claimPrivateKey = generatePrivateKey();
  const account = privateKeyToAccount(claimPrivateKey);
  const claimAddress = account.address;

  // Derive claimKeyHash: keccak256(abi.encodePacked(claimAddress))
  const claimKeyHash = keccak256(encodePacked(["address"], [claimAddress]));

  return {
    claimPrivateKey,
    claimAddress,
    claimKeyHash,
  };
}

/**
 * Derives the claimKeyHash from a known ephemeral private key or address.
 */
export function deriveClaimKeyHash(claimAddressOrKey: `0x${string}`): `0x${string}` {
  if (claimAddressOrKey.length === 66) {
    // It's a 32-byte private key
    const account = privateKeyToAccount(claimAddressOrKey);
    return keccak256(encodePacked(["address"], [account.address]));
  }
  // It's already an Ethereum address
  return keccak256(encodePacked(["address"], [claimAddressOrKey as Address]));
}

/**
 * Signs the claim payload using the ephemeral claim private key.
 * Message format: keccak256(abi.encodePacked(claimKeyHash, recipientAddress))
 */
export async function signClaimPayload(params: {
  claimPrivateKey: `0x${string}`;
  claimKeyHash: `0x${string}`;
  recipientAddress: Address;
}): Promise<`0x${string}`> {
  const account = privateKeyToAccount(params.claimPrivateKey);

  // Message = keccak256(abi.encodePacked(claimKeyHash, recipient))
  const messageHash = keccak256(
    encodePacked(
      ["bytes32", "address"],
      [params.claimKeyHash, params.recipientAddress]
    )
  );

  // Ethereum signed message
  const signature = await account.signMessage({
    message: { raw: messageHash },
  });

  return signature;
}

/**
 * Verifies that a signature for an escrow claim was generated by the holder of the claim key.
 */
export async function verifyClaimSignature(params: {
  claimKeyHash: `0x${string}`;
  recipientAddress: Address;
  signature: `0x${string}`;
}): Promise<{ valid: boolean; recoveredAddress?: Address }> {
  try {
    const messageHash = keccak256(
      encodePacked(
        ["bytes32", "address"],
        [params.claimKeyHash, params.recipientAddress]
      )
    );

    const recoveredAddress = await recoverMessageAddress({
      message: { raw: messageHash },
      signature: params.signature,
    });

    const expectedHash = keccak256(encodePacked(["address"], [recoveredAddress]));
    const valid = expectedHash.toLowerCase() === params.claimKeyHash.toLowerCase();

    return { valid, recoveredAddress };
  } catch (_err) {
    return { valid: false };
  }
}
